/*
###############################################################
#  Generated by:      Cadence Innovus 18.10-p002_1
#  OS:                Linux x86_64(Host ID vlsipool-j12.eecs.umich.edu)
#  Generated on:      Mon Oct 26 17:19:57 2020
#  Design:            temp_hd_inv8_header3
#  Command:           saveNetlist -excludeLeafCell -phys -excludeCellInst {sky130_fd_sc_hd__tapvpwrvgnd_1 sky130_fd_sc_hd__tap_3 sky130_fd_sc_hd__fill_1 sky130_fd_sc_hd__fill_2 sky130_fd_sc_hd__fill_4 sky130_fd_sc_hd__fill_8 sky130_fd_sc_hd__diode_2} /afs/eecs.umich.edu/vlsida/projects/FASoC/VERIF/GF12/fasoc_push/fasoc2/private/generators/temp-sense-gen/flow/results/innovus/temp_hd_inv8_header3.lvs.v
###############################################################
*/
module temp_hd_inv8_header3_TEMP_ANALOG_lv_0 (
	EN, 
	OUT, 
	OUTB, 
	VIN, 
	VSS);
   input EN;
   output OUT;
   output OUTB;
   inout VIN;
   inout VSS;

   // Internal wires
   wire n9;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire nx1;
   wire nx2;
   wire nx3;
   wire nb2;
   wire nb1;

   // Module instantiations
   sky130_fd_sc_hd__nand2_1 a_nand_0 (
	.A(EN),
	.B(n9),
	.Y(n1), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_0 (
	.A(n1),
	.Y(n2), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_1 (
	.A(n2),
	.Y(n3), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_2 (
	.A(n3),
	.Y(n4), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_3 (
	.A(n4),
	.Y(n5), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_4 (
	.A(n5),
	.Y(n6), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_5 (
	.A(n6),
	.Y(n7), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_6 (
	.A(n7),
	.Y(n8), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_7 (
	.A(n8),
	.Y(n9), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_m1 (
	.A(n9),
	.Y(nx1), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_m2 (
	.A(n9),
	.Y(nx2), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_1 a_inv_m3 (
	.A(nx2),
	.Y(nx3), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__buf_1 a_buf_3 (
	.A(nx3),
	.X(nb2), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__buf_1 a_buf_0 (
	.A(nx1),
	.X(nb1), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__buf_1 a_buf_1 (
	.A(nb1),
	.X(OUT), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__buf_1 a_buf_2 (
	.A(nb2),
	.X(OUTB), 
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS));

   // Fillers and physical instances.
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_12 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_11 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_10 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_9 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_8 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_7 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_6 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_5 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_4 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_3 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_2 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_TEMPANALOG_1 (
	.VPWR(VIN), 
	.VPB(VIN), 
	.VNB(VSS), 
	.VGND(VSS) );
endmodule

module temp_hd_inv8_header3_counter_0 (
	RESET_COUNTERn, 
	CLK_REF, 
	CLK_SENS, 
	SEL_CONV_TIME, 
	DONE, 
	DOUT, 
	VDD, 
	VSS);
   input RESET_COUNTERn;
   input CLK_REF;
   input CLK_SENS;
   input [3:0] SEL_CONV_TIME;
   output DONE;
   output [23:0] DOUT;
   inout VDD;
   inout VSS;

   // Internal wires
   wire clk_sens_in;
   wire done_ref;
   wire clk_ref_in;
   wire WAKE_pre;
   wire WAKE;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire [23:0] div_s;
   wire [20:0] div_r;

   // Module instantiations
   sky130_fd_sc_hd__and2_0 C609 (
	.A(done_ref),
	.B(CLK_REF),
	.X(clk_ref_in), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtp_1 WAKE_pre_reg (
	.CLK(CLK_REF),
	.D(n66),
	.Q(WAKE_pre),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtp_1 WAKE_reg (
	.CLK(CLK_REF),
	.D(n67),
	.Q(WAKE),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtp_1 div_s_reg_0_ (
	.CLK(clk_sens_in),
	.D(n68),
	.Q(div_s[0]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_20_ (
	.CLK_N(div_r[19]),
	.D(n112),
	.Q(div_r[20]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_1_ (
	.CLK_N(div_s[0]),
	.D(n69),
	.Q(div_s[1]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_2_ (
	.CLK_N(div_s[1]),
	.D(n70),
	.Q(div_s[2]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_3_ (
	.CLK_N(div_s[2]),
	.D(n71),
	.Q(div_s[3]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_4_ (
	.CLK_N(div_s[3]),
	.D(n72),
	.Q(div_s[4]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_5_ (
	.CLK_N(div_s[4]),
	.D(n73),
	.Q(div_s[5]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_6_ (
	.CLK_N(div_s[5]),
	.D(n74),
	.Q(div_s[6]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_7_ (
	.CLK_N(div_s[6]),
	.D(n75),
	.Q(div_s[7]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_8_ (
	.CLK_N(div_s[7]),
	.D(n76),
	.Q(div_s[8]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_9_ (
	.CLK_N(div_s[8]),
	.D(n77),
	.Q(div_s[9]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_10_ (
	.CLK_N(div_s[9]),
	.D(n78),
	.Q(div_s[10]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_11_ (
	.CLK_N(div_s[10]),
	.D(n79),
	.Q(div_s[11]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_12_ (
	.CLK_N(div_s[11]),
	.D(n80),
	.Q(div_s[12]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_13_ (
	.CLK_N(div_s[12]),
	.D(n81),
	.Q(div_s[13]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_14_ (
	.CLK_N(div_s[13]),
	.D(n82),
	.Q(div_s[14]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_15_ (
	.CLK_N(div_s[14]),
	.D(n83),
	.Q(div_s[15]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_16_ (
	.CLK_N(div_s[15]),
	.D(n84),
	.Q(div_s[16]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_17_ (
	.CLK_N(div_s[16]),
	.D(n85),
	.Q(div_s[17]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_18_ (
	.CLK_N(div_s[17]),
	.D(n86),
	.Q(div_s[18]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_19_ (
	.CLK_N(div_s[18]),
	.D(n87),
	.Q(div_s[19]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_20_ (
	.CLK_N(div_s[19]),
	.D(n88),
	.Q(div_s[20]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_21_ (
	.CLK_N(div_s[20]),
	.D(n89),
	.Q(div_s[21]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_22_ (
	.CLK_N(div_s[21]),
	.D(n90),
	.Q(div_s[22]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_s_reg_23_ (
	.CLK_N(div_s[22]),
	.D(n91),
	.Q(div_s[23]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_1_ (
	.CLK_N(div_r[0]),
	.D(n93),
	.Q(div_r[1]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_2_ (
	.CLK_N(div_r[1]),
	.D(n94),
	.Q(div_r[2]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_3_ (
	.CLK_N(div_r[2]),
	.D(n95),
	.Q(div_r[3]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_4_ (
	.CLK_N(div_r[3]),
	.D(n96),
	.Q(div_r[4]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_5_ (
	.CLK_N(div_r[4]),
	.D(n97),
	.Q(div_r[5]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_6_ (
	.CLK_N(div_r[5]),
	.D(n98),
	.Q(div_r[6]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_7_ (
	.CLK_N(div_r[6]),
	.D(n99),
	.Q(div_r[7]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_8_ (
	.CLK_N(div_r[7]),
	.D(n100),
	.Q(div_r[8]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_9_ (
	.CLK_N(div_r[8]),
	.D(n101),
	.Q(div_r[9]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_10_ (
	.CLK_N(div_r[9]),
	.D(n102),
	.Q(div_r[10]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_11_ (
	.CLK_N(div_r[10]),
	.D(n103),
	.Q(div_r[11]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_12_ (
	.CLK_N(div_r[11]),
	.D(n104),
	.Q(div_r[12]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_13_ (
	.CLK_N(div_r[12]),
	.D(n105),
	.Q(div_r[13]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_14_ (
	.CLK_N(div_r[13]),
	.D(n106),
	.Q(div_r[14]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_15_ (
	.CLK_N(div_r[14]),
	.D(n107),
	.Q(div_r[15]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_16_ (
	.CLK_N(div_r[15]),
	.D(n108),
	.Q(div_r[16]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_17_ (
	.CLK_N(div_r[16]),
	.D(n109),
	.Q(div_r[17]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_18_ (
	.CLK_N(div_r[17]),
	.D(n110),
	.Q(div_r[18]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtn_1 div_r_reg_19_ (
	.CLK_N(div_r[18]),
	.D(n111),
	.Q(div_r[19]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__dfrtp_1 div_r_reg_0_ (
	.CLK(clk_ref_in),
	.D(n92),
	.Q(div_r[0]),
	.RESET_B(RESET_COUNTERn), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U3 (
	.A(div_r[15]),
	.Y(n107), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U4 (
	.A(SEL_CONV_TIME[0]),
	.Y(n1), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_2 U5 (
	.A(SEL_CONV_TIME[1]),
	.Y(n8), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_2 U6 (
	.A(div_r[8]),
	.Y(n100), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_2 U7 (
	.A(div_r[7]),
	.Y(n99), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_2 U8 (
	.A(div_r[6]),
	.Y(n98), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_2 U9 (
	.A(div_r[5]),
	.Y(n97), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_2 U10 (
	.A(n10),
	.Y(n15), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__a21o_1 U11 (
	.A1(n99),
	.A2(n11),
	.B1(n8),
	.X(n4), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U12 (
	.A(DONE),
	.Y(n23), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__inv_2 U13 (
	.A(div_r[13]),
	.Y(n105), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U14 (
	.A(div_s[21]),
	.Y(n89), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U15 (
	.A(div_s[6]),
	.Y(n74), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__conb_1 U16 (
	.HI(n66), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U17 (
	.A(SEL_CONV_TIME[2]),
	.B(SEL_CONV_TIME[0]),
	.Y(n11), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__a21oi_1 U18 (
	.A1(n11),
	.A2(n97),
	.B1(SEL_CONV_TIME[1]),
	.Y(n7), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U19 (
	.A(SEL_CONV_TIME[2]),
	.B(n1),
	.Y(n10), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nand2_1 U20 (
	.A(SEL_CONV_TIME[2]),
	.B(n1),
	.Y(n14), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nand2_1 U21 (
	.A(SEL_CONV_TIME[2]),
	.B(SEL_CONV_TIME[0]),
	.Y(n13), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__o22ai_1 U22 (
	.A1(div_r[9]),
	.A2(n14),
	.B1(div_r[10]),
	.B2(n13),
	.Y(n2), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__a21oi_1 U23 (
	.A1(n10),
	.A2(n98),
	.B1(n2),
	.Y(n6), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__o22ai_1 U24 (
	.A1(div_r[11]),
	.A2(n14),
	.B1(div_r[12]),
	.B2(n13),
	.Y(n3), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__a211oi_1 U25 (
	.A1(n10),
	.A2(n100),
	.B1(n4),
	.C1(n3),
	.Y(n5), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__a21oi_1 U26 (
	.A1(n7),
	.A2(n6),
	.B1(n5),
	.Y(n22), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__a21oi_1 U27 (
	.A1(n11),
	.A2(n107),
	.B1(n8),
	.Y(n9), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__o21ai_1 U28 (
	.A1(div_r[20]),
	.A2(n13),
	.B1(n9),
	.Y(n19), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__o22ai_1 U29 (
	.A1(div_r[19]),
	.A2(n14),
	.B1(div_r[16]),
	.B2(n15),
	.Y(n18), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__a21oi_1 U30 (
	.A1(n11),
	.A2(n105),
	.B1(SEL_CONV_TIME[1]),
	.Y(n12), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__o21ai_1 U31 (
	.A1(div_r[18]),
	.A2(n13),
	.B1(n12),
	.Y(n17), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__o22ai_1 U32 (
	.A1(div_r[14]),
	.A2(n15),
	.B1(div_r[17]),
	.B2(n14),
	.Y(n16), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__o22ai_1 U33 (
	.A1(n19),
	.A2(n18),
	.B1(n17),
	.B2(n16),
	.Y(n20), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nand2_1 U34 (
	.A(SEL_CONV_TIME[3]),
	.B(n20),
	.Y(n21), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__o21ai_1 U35 (
	.A1(n22),
	.A2(SEL_CONV_TIME[3]),
	.B1(n21),
	.Y(DONE), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__and3_1 U36 (
	.A(WAKE_pre),
	.B(n23),
	.C(CLK_SENS),
	.X(clk_sens_in), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__and2_0 U37 (
	.A(WAKE),
	.B(n23),
	.X(done_ref), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__or2_0 U38 (
	.A(WAKE_pre),
	.B(WAKE),
	.X(n67), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U39 (
	.A(div_s[0]),
	.Y(n68), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U40 (
	.A(n23),
	.B(n68),
	.Y(DOUT[0]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U41 (
	.A(div_s[1]),
	.Y(n69), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U42 (
	.A(n23),
	.B(n69),
	.Y(DOUT[1]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U43 (
	.A(div_s[2]),
	.Y(n70), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U44 (
	.A(n23),
	.B(n70),
	.Y(DOUT[2]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U45 (
	.A(div_s[3]),
	.Y(n71), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U46 (
	.A(n23),
	.B(n71),
	.Y(DOUT[3]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U47 (
	.A(div_s[4]),
	.Y(n72), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U48 (
	.A(n23),
	.B(n72),
	.Y(DOUT[4]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U49 (
	.A(div_s[5]),
	.Y(n73), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U50 (
	.A(n23),
	.B(n73),
	.Y(DOUT[5]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U51 (
	.A(n23),
	.B(n74),
	.Y(DOUT[6]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U52 (
	.A(div_s[7]),
	.Y(n75), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U53 (
	.A(n23),
	.B(n75),
	.Y(DOUT[7]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U54 (
	.A(div_s[8]),
	.Y(n76), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U55 (
	.A(n23),
	.B(n76),
	.Y(DOUT[8]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U56 (
	.A(div_s[9]),
	.Y(n77), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U57 (
	.A(n23),
	.B(n77),
	.Y(DOUT[9]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U58 (
	.A(div_s[10]),
	.Y(n78), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U59 (
	.A(n23),
	.B(n78),
	.Y(DOUT[10]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U60 (
	.A(div_s[11]),
	.Y(n79), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U61 (
	.A(n23),
	.B(n79),
	.Y(DOUT[11]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U62 (
	.A(div_s[12]),
	.Y(n80), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U63 (
	.A(n23),
	.B(n80),
	.Y(DOUT[12]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U64 (
	.A(div_s[13]),
	.Y(n81), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U65 (
	.A(n23),
	.B(n81),
	.Y(DOUT[13]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U66 (
	.A(div_s[14]),
	.Y(n82), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U67 (
	.A(n23),
	.B(n82),
	.Y(DOUT[14]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U68 (
	.A(div_s[15]),
	.Y(n83), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U69 (
	.A(n23),
	.B(n83),
	.Y(DOUT[15]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U70 (
	.A(div_s[16]),
	.Y(n84), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U71 (
	.A(n23),
	.B(n84),
	.Y(DOUT[16]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U72 (
	.A(div_s[17]),
	.Y(n85), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U73 (
	.A(n23),
	.B(n85),
	.Y(DOUT[17]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U74 (
	.A(div_s[18]),
	.Y(n86), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U75 (
	.A(n23),
	.B(n86),
	.Y(DOUT[18]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U76 (
	.A(div_s[19]),
	.Y(n87), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U77 (
	.A(n23),
	.B(n87),
	.Y(DOUT[19]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U78 (
	.A(div_s[20]),
	.Y(n88), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U79 (
	.A(n23),
	.B(n88),
	.Y(DOUT[20]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U80 (
	.A(n23),
	.B(n89),
	.Y(DOUT[21]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U81 (
	.A(div_s[22]),
	.Y(n90), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U82 (
	.A(n23),
	.B(n90),
	.Y(DOUT[22]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U83 (
	.A(div_s[23]),
	.Y(n91), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__nor2_1 U84 (
	.A(n23),
	.B(n91),
	.Y(DOUT[23]), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U85 (
	.A(div_r[20]),
	.Y(n112), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U86 (
	.A(div_r[19]),
	.Y(n111), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U87 (
	.A(div_r[0]),
	.Y(n92), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U88 (
	.A(div_r[1]),
	.Y(n93), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U89 (
	.A(div_r[2]),
	.Y(n94), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U90 (
	.A(div_r[3]),
	.Y(n95), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U91 (
	.A(div_r[4]),
	.Y(n96), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U92 (
	.A(div_r[9]),
	.Y(n101), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U93 (
	.A(div_r[10]),
	.Y(n102), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U94 (
	.A(div_r[11]),
	.Y(n103), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U95 (
	.A(div_r[12]),
	.Y(n104), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U96 (
	.A(div_r[14]),
	.Y(n106), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U97 (
	.A(div_r[16]),
	.Y(n108), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U98 (
	.A(div_r[17]),
	.Y(n109), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   sky130_fd_sc_hd__clkinv_1 U99 (
	.A(div_r[18]),
	.Y(n110), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
endmodule

module temp_hd_inv8_header3_TEMP_ANALOG_hv_0 (
	CLK_REF, 
	RESET_COUNTERn, 
	SEL_CONV_TIME, 
	en, 
	out, 
	outb, 
	DOUT, 
	DONE, 
	lc_out, 
	VIN, 
	VDD, 
	VSS);
   input CLK_REF;
   input RESET_COUNTERn;
   input [3:0] SEL_CONV_TIME;
   input en;
   input out;
   input outb;
   output [23:0] DOUT;
   output DONE;
   output lc_out;
   inout VIN;
   inout VDD;
   inout VSS;

   // Module instantiations
   temp_hd_inv8_header3_counter_0 async_counter_0 (
	.RESET_COUNTERn(RESET_COUNTERn),
	.CLK_REF(CLK_REF),
	.CLK_SENS(lc_out),
	.SEL_CONV_TIME(SEL_CONV_TIME),
	.DONE(DONE),
	.DOUT(DOUT), 
	.VDD(VDD), 
	.VSS(VSS));
   HEADER a_header_0 (
	.VIN(VIN), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   HEADER a_header_1 (
	.VIN(VIN), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   HEADER a_header_2 (
	.VIN(VIN), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
   SLC a_lc_0 (
	.IN(out),
	.INB(outb),
	.VOUT(lc_out), 
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS));
endmodule

module temp_hd_inv8_header3 (
	CLK_REF, 
	RESET_COUNTERn, 
	SEL_CONV_TIME, 
	en, 
	DOUT, 
	DONE, 
	out, 
	outb, 
	lc_out, 
	VSS, 
	VDD);
   input CLK_REF;
   input RESET_COUNTERn;
   input [3:0] SEL_CONV_TIME;
   input en;
   output [23:0] DOUT;
   output DONE;
   output out;
   output outb;
   output lc_out;
   inout VSS;
   inout VDD;

   // Internal wires
   wire VIN;
   wire VPW;
   wire VSSE;
   wire VNW;
   wire VDDPE;
   wire VDDCE;
   wire DVDD;

   // Module instantiations
   temp_hd_inv8_header3_TEMP_ANALOG_lv_0 temp_analog_0 (
	.EN(en),
	.OUT(out),
	.OUTB(outb), 
	.VIN(VIN), 
	.VSS(VSS));
   temp_hd_inv8_header3_TEMP_ANALOG_hv_0 temp_analog_1 (
	.CLK_REF(CLK_REF),
	.RESET_COUNTERn(RESET_COUNTERn),
	.SEL_CONV_TIME(SEL_CONV_TIME),
	.out(out),
	.outb(outb),
	.DOUT(DOUT),
	.DONE(DONE),
	.lc_out(lc_out),
	.VIN(VIN), 
	.VDD(VDD), 
	.VSS(VSS));

   // Fillers and physical instances.
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_56 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_55 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_54 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_53 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_52 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_51 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_50 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_49 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_48 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_47 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_46 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_45 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_44 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_43 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_42 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_41 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_40 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_39 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_38 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_37 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_36 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_35 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_34 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_33 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_32 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_31 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_30 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_29 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_28 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_27 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_26 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_25 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_24 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_23 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_22 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_21 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_20 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_19 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_18 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_17 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_16 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_15 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_14 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_13 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_12 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_11 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_10 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_9 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_8 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_7 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_6 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_5 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_4 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_3 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_2 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
   sky130_fd_sc_hd__decap_3 ENDCAP_CORE_1 (
	.VPWR(VDD), 
	.VPB(VDD), 
	.VNB(VSS), 
	.VGND(VSS) );
endmodule

